apiVersion: v1
kind: Service
metadata:
  name: inlets
  labels:
    talk: starting-k8s-with-k3s-on-pi
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    talk: starting-k8s-with-k3s-on-pi
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: ingress
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /
        backend:
          serviceName: ingress
          servicePort: 8080
